[package]
name = "fzn2lp"
version = "0.1.0pre"
authors = ["Sven Thiele <sthiele78@gmail.com>"]
description = "A FlatZinc to AnsProlog converter"
readme = "README.md"
repository = "https://github.com/sthiele/fzn2lp"
license = "MIT"
edition = "2018"
exclude = ["/.github"]

[dependencies]
nom = "5.1"
flatzinc = { path = "../flatzinc" }
structopt = "0.3"
anyhow = "1.0"